name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download Branch
      uses: actions/checkout@v2

    - name: Update Submodule
      run: |
        git submodule init
        git submodule update --remote

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: "20.x"

    - name: Install NodeModules
      run: |
        rm -f .yarnclean yarn.lock
        yarn --non-interactive --silent
        yarn list --depth=0

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Hexo Generate
      run: |
        rm -rf ./public
        yarn run hexo clean
        yarn run hexo generate

    - name: Upload to COS
      uses: zkqiang/tencent-cos-action@master
      with:
        commands: |  # 使用 `|` 表示依次执行多条命令
          rm -r -f cos://${{ secrets.COS_BUCKET }}/
          cp -r ./public/ cos://${{ secrets.COS_BUCKET }}/
        secret_id: ${{ secrets.COS_SECRET_ID }}
        secret_key: ${{ secrets.COS_SECRET_KEY }}
        bucket: ${{ secrets.COS_BUCKET }}
        region: ${{ secrets.COS_REGION }}
