name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Download Branch
      uses: actions/checkout@v6.0.2
      with:
        submodules: true

    - name: Setup Node
      uses: actions/setup-node@v6.3.0

    - name: Install NodeModules
      run: |
        rm -f .yarnclean yarn.lock
        yarn --non-interactive --silent
        yarn list --depth=0

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Hexo Generate
      run: |
        rm -rf ./public
        yarn run hexo clean
        yarn run hexo generate

    - name: Archive artifact
      run: |
        tar \
          --dereference --hard-dereference \
          --directory ./public \
          -cvf artifact.tar \
          --exclude=.git \
          --exclude=.github \
          .

    - name: Upload Artifact
      uses: actions/upload-artifact@v7
      with:
        name: github-pages
        path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v6.0.0
    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3.0.2-node.24
